dist: trusty
sudo: false
language: java
jdk:
  - openjdk11
node_js:
  - '13'
addons:
  chrome: stable
cache:
  - npm
  directories:
    - 'hackathon-web/src/main/web/node'
    - 'hackathon-web/src/main/web/node-modules'
    - '$HOME/.m2'
    - '/home/travis/.sonar/cache'
install:
  - 'npm install -g @angular/cli'
script:
  - 'mvn clean'
  - 'mvn test'
  - 'mvn install -DskipTests=true'