dist: trusty
os: linux
language: java
jdk:
  - openjdk11
node_js:
  - 13
addons:
  chrome: stable
cache:
  directories:
    - "hackathon-web/src/main/web/node"
    - "hackathon-web/src/main/web/node-modules"
    - "$HOME/.m2"
    - "/home/travis/.sonar/cache"
install:
  - "npm install -g @angular/cli"
before_script:
  - "sudo chmod +x build.sh"
  - "sudo chmod +x run.sh"
script:
  - "./build.sh"