dist: trusty
os: linux
language: java
jdk:
  - openjdk11
node_js:
  - 13
addons:
  chrome: stable
before_cache:
  - "rm -rf $HOME/.m2/repository/com/fw/hackathon"
cache:
  directories:
    - "hackathon-web/src/main/web/node"
    - "hackathon-web/src/main/web/node-modules"
    - "$HOME/.m2"
install:
  - "npm install -g @angular/cli"
before_script:
  - "sudo chmod +x build.sh"
  - "sudo chmod +x run.sh"
script:
  - "./build.sh"